language: node_js

# "Please note that as of July 2019, npm is cached by default on Travis CI"
cache:
  npm: false

node_js:
  - "node"
  - "8"
  - "6"
sudo: false
install:
  - npm install
  - npm install -g codecov
  - lerna bootstrap
  - npm run babel
script:
  - npm run coverage
after_success:
  - codecov
